artworks:
  - id: "abstrait"
    title: "Abstraction Moderne"
    description: "Une œuvre abstraite exprimant les émotions à travers les formes et les couleurs."
    dimensions: "50x70 cm"
    image: "abstrait.jpg"
    category: "Abstrait"
    
  - id: "bateau"
    title: "Navigation"
    description: "Une peinture maritime capturant l'essence de la navigation et des horizons infinis."
    dimensions: "60x80 cm"
    image: "bateau.jpg"
    category: "Paysage"
    
  - id: "beach"
    title: "Plage Sereine"
    description: "Un paysage côtier paisible évoquant la tranquillité des bords de mer."
    dimensions: "50x70 cm"
    image: "beach.jpg"
    category: "Paysage"
    
  - id: "boujie"
    title: "Élégance"
    description: "Une œuvre sophistiquée reflétant le raffinement et l'élégance artistique."
    dimensions: "40x60 cm"
    image: "boujie.jpg"
    category: "Portrait"
    
  - id: "collection"
    title: "Collection Privée"
    description: "Une pièce unique faisant partie d'une collection artistique personnelle."
    dimensions: "55x75 cm"
    image: "collection.jpg"
    category: "Abstrait"
    
  - id: "oiseaux"
    title: "Envol"
    description: "Représentation artistique des oiseaux symbolisant la liberté et l'évasion."
    dimensions: "45x65 cm"
    image: "oiseaux.jpg"
    category: "Nature"
    
  - id: "vase"
    title: "Nature Morte"
    description: "Étude contemplative d'objets du quotidien transformés en art."
    dimensions: "40x50 cm"
    image: "vase.jpg"
    category: "Nature Morte"
    
  - id: "fenetre"
    title: "Fenêtre sur l'Art"
    description: "Une perspective unique offrant une vue artistique sur le monde extérieur."
    dimensions: "50x70 cm"
    image: "fenetre.jpg"
    category: "Abstrait"
    
  - id: "la_ghaleb"
    title: "La Ghaleb"
    description: "Une œuvre inspirée des traditions artistiques, mêlant modernité et héritage culturel."
    dimensions: "60x80 cm"
    image: "la_ghaleb.jpg"
    category: "Culturel"
    
  - id: "majorelle"
    title: "Jardin Majorelle"
    description: "Inspiration puisée dans les couleurs vibrantes et l'atmosphère unique du célèbre jardin."
    dimensions: "55x75 cm"
    image: "majorelle.jpg"
    category: "Paysage"
    
  - id: "montagne"
    title: "Paysage Montagnard"
    description: "Représentation majestueuse des sommets et de la beauté naturelle des montagnes."
    dimensions: "65x85 cm"
    image: "montagne.jpg"
    category: "Paysage"
    
  - id: "yellow_flower"
    title: "Fleur Dorée"
    description: "Célébration de la beauté florale avec des tons dorés éclatants et chaleureux."
    dimensions: "45x60 cm"
    image: "yellow_flower.jpg"
    category: "Nature"
    
  - id: "coucher_soleil"
    title: "Coucher de Soleil"
    description: "Capture poétique des dernières lueurs du jour, peignant le ciel de couleurs chatoyantes."
    dimensions: "70x90 cm"
    image: "coucher_soleil.jpg"
    category: "Paysage"
    
  - id: "dessin_gibli"
    title: "Inspiration Ghibli"
    description: "Hommage artistique à l'univers enchanteur du Studio Ghibli, mêlant rêve et réalité."
    dimensions: "50x65 cm"
    image: "dessin_gibli.jpg"
    category: "Illustration"
    
  - id: "fleurs_jaune"
    title: "Bouquet Lumineux"
    description: "Explosion de couleurs jaunes célébrant la joie et la vitalité des fleurs printanières."
    dimensions: "40x55 cm"
    image: "fleurs_jaune.jpg"
    category: "Nature"
    
  - id: "vase_bleu"
    title: "Vase Azur"
    description: "Nature morte élégante mettant en valeur les nuances subtiles du bleu et la beauté des formes simples."
    dimensions: "35x50 cm"
    image: "vase_bleu.jpg"
    category: "Nature Morte"
    
  
